const data = {
  products: [
    {
      _id: "1",
      name: "IPHONE SE 64 GB BLACK",
      category: "Telephone",
      image: "/images/iphone_se_qara-1-removebg-preview.png",
      price: 1099,
      priceDiscount: 999,
      brand: "Iphone",
      MP: 12,
      RAM: 3,
      OS: "IOS 13",
      INCH: 4.7,
      mAH: 1821,
      memory: "64 GB",
      screen: "IPS LCD",
      SIM: 1,
    },
    {
      _id: "2",
      name: "IPHONE SE 128 GB BLACK",
      category: "Telephone",
      image: "/images/iphone_se_qara-1-removebg-preview.png",
      price: 1239,
      brand: "Iphone",
      MP: 12,
      RAM: 3,
      OS: "IOS 13",
      INCH: 4.7,
      mAH: 1821,
      memory: "128 GB",
      screen: "IPS LCD",
      SIM: 1,
    },
    {
      _id: "3",
      name: "IPHONE 11 64 GB BLACK",
      category: "Telephone",
      image: "/images/iphone11_black-1-removebg-preview.png",
      price: 1239,
      brand: "Iphone",
      MP: 24,
      RAM: 4,
      OS: "IOS 13",
      INCH: 6.1,
      mAH: 3046,
      memory: "64 GB",
      screen: "IPS LCD",
      SIM: 1,
    },
    {
      _id: "4",
      name: "IPHONE 12 mini 64 GB BLACK",
      category: "Telephone",
      image: "/images/12mini_black-1-removebg-preview.png",
      price: 1799,
      brand: "Iphone",
      MP: 24,
      RAM: 4,
      OS: "IOS 14.1",
      INCH: 5.4,
      mAH: 2227,
      memory: "64 GB",
      screen: "XDR OLED",
      SIM: 1,
    },
    {
      _id: "5",
      name: "IPHONE 11 128 GB BLACK",
      category: "Telephone",
      image: "/images/iphone11_black-1-removebg-preview.png",
      price: 1819,
      brand: "Iphone",
      MP: 24,
      RAM: 4,
      OS: "IOS 13",
      INCH: 6.1,
      mAH: 3046,
      memory: "128 GB",
      screen: "IPS LCD",
      SIM: 1,
    },
    {
      _id: "6",
      name: "IPHONE 12 mini 128 GB BLACK",
      category: "Telephone",
      image: "/images/12mini_black-1-removebg-preview.png",
      price: 1929,
      brand: "Iphone",
      MP: 24,
      RAM: 4,
      OS: "IOS 14.1",
      INCH: 5.4,
      mAH: 2227,
      memory: "128 GB",
      screen: "XDR OLED",
      SIM: 1,
    },
    {
      _id: "7",
      name: "iPhone XS Max 64 GB Space Gray",
      category: "Telephone",
      image: "/images/xsmaxspacegrey-1-removebg-preview.png",
      price: 1999,
      brand: "Iphone",
      MP: 12,
      RAM: 4,
      OS: "IOS 12",
      INCH: 6.5,
      mAH: 3174,
      memory: "64 GB",
      screen: "OLED HDR",
      SIM: 1,
    },
    {
      _id: "8",
      name: "iPhone 11 Pro 64 GB Grey",
      category: "Telephone",
      image: "/images/iphone11pro_grey-1-removebg-preview.png",
      price: 2549,
      brand: "Iphone",
      MP: 36,
      RAM: 4,
      OS: "IOS 13",
      INCH: 5.8,
      mAH: 3190,
      memory: "64 GB",
      screen: "OLED touchscreen",
      SIM: 1,
    },
    {
      _id: "9",
      name: "iPhone 12 Pro 128 GB Gold",
      category: "Telephone",
      image: "/images/12pro_gold-1-removebg-preview.png",
      price: 2669,
      brand: "Iphone",
      MP: 36,
      RAM: 6,
      OS: "IOS 14.1",
      INCH: 6.1,
      mAH: 2815,
      memory: "128 GB",
      screen: "XDR OLED",
      SIM: 1,
    },
    {
      _id: "10",
      name: "iPhone 11 Pro Max 64 GB Green",
      category: "Telephone",
      image: "/images/iphone11promax_green-1-removebg-preview.png",
      price: 2699,
      brand: "Iphone",
      MP: 36,
      RAM: 4,
      OS: "IOS 13",
      INCH: 6.5,
      mAH: 3969,
      memory: "64 GB",
      screen: "XDR OLED",
      SIM: 1,
    },
    {
      _id: "11",
      name: "iPhone 12 Pro Max 256 GB Blue",
      category: "Telephone",
      image: "/images/12promax_blue-1-removebg-preview.png",
      price: 3229,
      brand: "Iphone",
      MP: 36,
      RAM: 6,
      OS: "IOS 14.1",
      INCH: 6.7,
      mAH: 3687,
      memory: "256 GB",
      screen: "XDR OLED",
      SIM: 1,
    },
    {
      _id: "12",
      name: "iPhone 12 Pro Max 512 GB Gold",
      category: "Telephone",
      image: "/images/12promax_gold-1-removebg-preview.png",
      price: 3769,
      brand: "Iphone",
      MP: 36,
      RAM: 6,
      OS: "IOS 14.1",
      INCH: 6.7,
      mAH: 3687,
      memory: "512 GB",
      screen: "XDR OLED",
      SIM: 1,
    },
    {
      _id: "13",
      name: "Samsung Galaxy A01 Core Black",
      category: "Telephone",
      image: "/images/a013_black-1-removebg-preview.png",
      price: 199,
      brand: "Samsung",
      MP: 8,
      RAM: 1,
      OS: "Android 10(Go edition)",
      INCH: 5.3,
      mAH: 3000,
      memory: "16 GB",
      screen: "PLS TFT",
      SIM: 2,
    },
    {
      _id: "14",
      name: "Samsung Galaxy A02 Black",
      category: "Telephone",
      image: "/images/a022_black-1-removebg-preview.png",
      price: 239,
      brand: "Samsung",
      MP: 15,
      RAM: 2,
      OS: "Android 10,One UI 2.0",
      INCH: 6.5,
      mAH: 5000,
      memory: "32 GB",
      screen: "PLS IPS",
      SIM: 2,
    },
    {
      _id: "15",
      name: "Samsung Galaxy A10s Dark Red",
      category: "Telephone",
      image: "/images/a107_red-3-removebg-preview.png",
      price: 269,
      brand: "Samsung",
      MP: 15,
      RAM: 2,
      OS: "Android 9.0(Pie)",
      INCH: 6.2,
      mAH: 4000,
      memory: "32 GB",
      screen: "IPS LCD",
      SIM: 2,
    },
    {
      _id: "16",
      name: "Samsung Galaxy A02s Black",
      category: "Telephone",
      image: "/images/a025_black-1-removebg-preview.png",
      price: 289,
      brand: "Samsung",
      MP: 17,
      RAM: 3,
      OS: "Android 10",
      INCH: 6.5,
      mAH: 5000,
      memory: "32 GB",
      screen: "PLS IPS",
      SIM: 2,
    },
    {
      _id: "17",
      name: "Samsung Galaxy A12 32GB Black",
      category: "Telephone",
      image: "/images/a125_black-1-removebg-preview.png",
      price: 329,
      brand: "Samsung",
      MP: 57,
      RAM: 3,
      OS: "Android 10",
      INCH: 6.5,
      mAH: 5000,
      memory: "32 GB",
      screen: "PLS IPS",
      SIM: 2,
    },
    {
      _id: "18",
      name: "Samsung Galaxy A21s 64 GB Blue",
      category: "Telephone",
      image: "/images/a217_blue-1-removebg-preview.png",
      price: 429,
      brand: "Samsung",
      MP: 60,
      RAM: 4,
      OS: "Android 10,One UI 2.0",
      INCH: 6.5,
      mAH: 5000,
      memory: "64 GB",
      screen: "PLS TFT",
      SIM: 2,
    },
    {
      _id: "19",
      name: "Samsung Galaxy A22 64GB Black",
      category: "Telephone",
      image: "/images/a225_black-1-removebg-preview.png",
      price: 499,
      brand: "Samsung",
      MP: 60,
      RAM: 4,
      OS: "Android 11",
      INCH: 6.4,
      mAH: 5000,
      memory: "64 GB",
      screen: "Super AMOLED",
      SIM: 2,
    },
    {
      _id: "20",
      name: "Samsung Galaxy A32 64GB Black",
      category: "Telephone",
      image: "/images/a325_black-1-removebg-preview.png",
      price: 539,
      brand: "Samsung",
      MP: 82,
      RAM: 4,
      OS: "Android 11,One UI 3.0",
      INCH: 6.4,
      mAH: 5000,
      memory: "64 GB",
      screen: "Super AMOLED",
      SIM: 2,
    },
    {
      _id: "21",
      name: "Samsung Galaxy A22 128GB Black",
      category: "Telephone",
      image: "/images/a225_black-1-removebg-preview.png",
      price: 549,
      brand: "Samsung",
      MP: 60,
      RAM: 4,
      OS: "Android 11",
      INCH: 6.4,
      mAH: 5000,
      memory: "128 GB",
      screen: "Super AMOLED",
      SIM: 2,
    },
    {
      _id: "22",
      name: "Samsung Galaxy A52 128GB Black",
      category: "Telephone",
      image: "/images/a525_black-1-removebg-preview.png",
      price: 719,
      brand: "Samsung",
      MP: 86,
      RAM: 4,
      OS: "Android 11,One UI 3.1",
      INCH: 6.5,
      mAH: 4500,
      memory: "128 GB",
      screen: "Super AMOLED",
      SIM: 2,
    },
    {
      _id: "23",
      name: "Samsung Galaxy A72 128GB Black",
      category: "Telephone",
      image: "/images/a725_black-1-removebg-preview.png",
      price: 999,
      priceDiscount: 919,
      brand: "Samsung",
      MP: 89,
      RAM: 6,
      OS: "Android 11,One UI 3.1",
      INCH: 6.7,
      mAH: 5000,
      memory: "128 GB",
      screen: "Super AMOLED",
      SIM: 2,
    },
    {
      _id: "24",
      name: "Samsung Galaxy Note 10 Lite Red",
      category: "Telephone",
      image: "/images/n770_red-1-removebg-preview.png",
      price: 1149,
      brand: "Samsung",
      MP: 36,
      RAM: 6,
      OS: "Android 10,One UI 2",
      INCH: 6.7,
      mAH: 4500,
      memory: "128 GB",
      screen: "Super AMOLED",
      SIM: 2,
    },
    {
      _id: "25",
      name: "Xiaomi Redmi 9 32GB Grey",
      category: "Telephone",
      image: "/images/redmi9_grey-1-removebg-preview.png",
      price: 329,
      brand: "Xiaomi",
      MP: 28,
      RAM: 3,
      OS: "Android 10,MIUI 12",
      INCH: 6.53,
      mAH: 5020,
      memory: "32 GB",
      screen: "IPS LCD",
      SIM: 2,
    },
    {
      _id: "26",
      name: "Xiaomi Poco M3 64GB Black",
      category: "Telephone",
      image: "/images/m3_black-1-removebg-preview.png",
      price: 399,
      brand: "Xiaomi",
      MP: 52,
      RAM: 4,
      OS: "Android 10,MIUI 12",
      INCH: 6.53,
      mAH: 6000,
      memory: "64 GB",
      screen: "IPS LCD",
      SIM: 2,
    },
    {
      _id: "27",
      name: "Xiaomi Redmi Note 9 64GB Grey",
      category: "Telephone",
      image: "/images/note9_grey-1-removebg-preview.png",
      price: 429,
      brand: "Xiaomi",
      MP: 60,
      RAM: 3,
      OS: "Android 10,MIUI 11",
      INCH: 6.53,
      mAH: 5020,
      memory: "64 GB",
      screen: "IPS LCD",
      SIM: 2,
    },
    {
      _id: "28",
      name: "Xiaomi Redmi Note 10 64GB Grey",
      category: "Telephone",
      image: "/images/note10_grey-1-removebg-preview.png",
      price: 499,
      brand: "Xiaomi",
      MP: 60,
      RAM: 4,
      OS: "Android 11,MIUI 12",
      INCH: 6.43,
      mAH: 5000,
      memory: "64 GB",
      screen: "Super AMOLED",
      SIM: 2,
    },
    {
      _id: "29",
      name: "Xiaomi Poco M3 Pro 5G 64GB Black",
      category: "Telephone",
      image: "/images/m3pro_black-1-removebg-preview.png",
      price: 529,
      brand: "Xiaomi",
      MP: 52,
      RAM: 4,
      OS: "Android 11,MIUI 12",
      INCH: 6.5,
      mAH: 5000,
      memory: "64 GB",
      screen: "IPS LCD",
      SIM: 2,
    },
    {
      _id: "30",
      name: "Xiaomi Redmi Note 10 128GB Grey",
      category: "Telephone",
      image: "/images/note10_grey-3-removebg-preview.png",
      price: 539,
      priceDiscount: 499,
      brand: "Xiaomi",
      MP: 60,
      RAM: 4,
      OS: "Android 11,MIUI 12",
      INCH: 6.5,
      mAH: 5000,
      memory: "128 GB",
      screen: "Super AMOLED",
      SIM: 2,
    },
    {
      _id: "31",
      name: "Honor 8A Prime 64 GB Black",
      category: "Telephone",
      image: "/images/8aprime_blackpng-1-removebg-preview.png",
      price: 349,
      brand: "Honor",
      MP: 13,
      RAM: 3,
      OS: "Android 9.0(Pie),EMUI 9",
      INCH: 6.09,
      mAH: 3020,
      memory: "64 GB",
      screen: "LCD capacitive touchscreen",
      SIM: 2,
    },
    {
      _id: "32",
      name: "Honor 10i Black",
      category: "Telephone",
      image: "/images/honor_10i-black-1-removebg-preview.png",
      price: 449,
      brand: "Honor",
      MP: 34,
      RAM: 4,
      OS: "Android 9.0(Pie),EMUI 9",
      INCH: 6.21,
      mAH: 3400,
      memory: "128 GB",
      screen: "LTPS IPS LCD",
      SIM: 2,
    },
    {
      _id: "33",
      name: "Honor 20 128 GB Black",
      category: "Telephone",
      image: "/images/honor20_black-1-removebg-preview.png",
      price: 799,
      brand: "Honor",
      MP: 65,
      RAM: 6,
      OS: "Android 9.0(Pie),Magic 2.1",
      INCH: 6.26,
      mAH: 3750,
      memory: "128 GB",
      screen: "IPS LCD",
      SIM: 2,
    },
    {
      _id: "34",
      name: "Honor 20 Pro 256 GB Phantome Blue",
      category: "Telephone",
      image: "/images/honor20_black-1-removebg-preview.png",
      price: 999,
      brand: "Honor",
      MP: 74,
      RAM: 8,
      OS: "Android 9.0(Pie),Magic 2.1",
      INCH: 6.26,
      mAH: 4000,
      memory: "256 GB",
      screen: "IPS LCD",
      SIM: 2,
    },
    {
      _id: "35",
      name: "Honor 30 128 GB Black",
      category: "Telephone",
      image: "/images/honor30_black-1-removebg-preview.png",
      price: 1149,
      brand: "Honor",
      MP: 58,
      RAM: 8,
      OS: "Android 9.0(Pie),Magic UI 3",
      INCH: 6.53,
      mAH: 4000,
      memory: "128 GB",
      screen: "OLED",
      SIM: 2,
    },
    {
      _id: "36",
      name: "Honor 30 256 GB Silver",
      category: "Telephone",
      image: "/images/honor30_silver-1-removebg-preview.png",
      price: 1249,
      priceDiscount: 1179,
      brand: "Honor",
      MP: 58,
      RAM: 8,
      OS: "Android 9.0(Pie),Magic UI 3",
      INCH: 6.53,
      mAH: 4000,
      memory: "256 GB",
      screen: "OLED",
      SIM: 2,
    },
    {
      _id: "37",
      name: "Oneplus N10 128GB Midnight Ice",
      category: "Telephone",
      image: "/images/n10_mice-1-removebg-preview.png",
      price: 719,
      brand: "Oneplus",
      MP: 76,
      RAM: 6,
      OS: "Android 10, OxygenOS 10.5",
      INCH: 6.49,
      mAH: 4300,
      memory: "128 GB",
      screen: "IPS LCD",
      SIM: 2,
    },
    {
      _id: "38",
      name: "OnePlus 8 Pro 128GB Black",
      category: "Telephone",
      image: "/images/oneplus8pro_black-1-removebg-preview.png",
      price: 2099,
      priceDiscount: 1999,
      brand: "Oneplus",
      MP: 109,
      RAM: 8,
      OS: "Android 10, OxygenOS 10.5",
      INCH: 6.78,
      mAH: 4510,
      memory: "128 GB",
      screen: "Fluid AMOLED",
      SIM: 2,
    },
    {
      _id: "39",
      name: "OnePlus 8 Pro 256GB Blue",
      category: "Telephone",
      image: "/images/oneplus8pro_blue-1-removebg-preview.png",
      price: 2099,
      brand: "Oneplus",
      MP: 109,
      RAM: 12,
      OS: "Android 10, OxygenOS 10.0",
      INCH: 6.78,
      mAH: 4510,
      memory: "256 GB",
      screen: "Fluid AMOLED",
      SIM: 2,
    },
    {
      _id: "40",
      name: "Nokia 106 Grey",
      category: "Telephone",
      image: "/images/nokia106_grey-1-removebg-preview.png",
      price: 55,
      brand: "Nokia",
      MP: "-  ",
      RAM: 4,
      OS: "-",
      INCH: 1.8,
      mAH: 800,
      memory: "4 MB",
      screen: "TFT",
      SIM: 2,
    },
    {
      _id: "41",
      name: "Nokia 1 Plus Black",
      category: "Telephone",
      image: "/images/nokia1plus_black-1-removebg-preview.png",
      price: 55,
      brand: "Nokia",
      MP: 8,
      RAM: 1,
      OS: "Android 9.0 Pie",
      INCH: 5.45,
      mAH: 2500,
      memory: "8 GB",
      screen: "IPS LCD",
      SIM: 2,
    },
    {
      _id: "42",
      name: "Apple Macbook Air 13.3 Silver (MVFK2)",
      category: "Computer",
      image: "/images/apple-macbook-air-13_1-1-removebg-preview.png",
      price: 2399,
      brand: "MacBook",
      MP: "Intel® Core™ i5 8th Gen", //Processor
      RAM: 8,
      OS: "MacOS",
      INCH: 13.3,
      mAH: 2, //USB
      memory: "128 GB SSD",
      screen: "(2560x1600) Retina LED",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "43",
      name: "Apple Macbook Air 13.3 Gold (MREF2LL)",
      category: "Computer",
      image: "/images/mref2-1-1_1-removebg-preview.png",
      price: 2599,
      brand: "MacBook",
      MP: "Intel® Core™ i5-8210Y", //Processor
      RAM: 8,
      OS: "MacOS",
      INCH: 13.3,
      mAH: 2, //USB
      memory: "256 GB SSD",
      screen: "(2560x1600) Retina LED",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "44",
      name: "Apple MacBook Air M1 (MGN93RU)",
      category: "Computer",
      image: "/images/1-1-removebg-preview.png",
      price: 2899,
      brand: "MacBook",
      MP: "Apple M1", //Processor
      RAM: 8,
      OS: "MacOS",
      INCH: 13.3,
      mAH: 2, //USB
      memory: "256 GB SSD",
      screen: "(2560x1600) Retina LED",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "45",
      name: "Apple Macbook Pro 13.3 Silver (MPXU2)",
      category: "Computer",
      image:
        "/images/apple_macbook_pro_13_3_silver_mpxu2ll_1-1-removebg-preview.png",
      price: 2999,
      brand: "MacBook",
      MP: "2.3 GHz Intel Core i5 Dual-Core", //Processor
      RAM: 8,
      OS: "MacOS",
      INCH: 13.3,
      mAH: 2, //USB
      memory: "256 GB SSD",
      screen: "(2560x1600) Retina LED",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "46",
      name: "Apple MacBook Air M1 (MGN73UA)",
      category: "Computer",
      image: "/images/apple-macbook-air-m1-mgn73ua_1-1-removebg-preview.png",
      price: 3499,
      brand: "MacBook",
      MP: "Apple M1", //Processor
      RAM: 8,
      OS: "MacOS",
      INCH: 13.3,
      mAH: 2, //USB
      memory: "512 GB SSD",
      screen: "(2560x1600) Retina LED",
      SIM: 8, //Nuve sayi
    },
    {
      _id: "47",
      name: "Apple MacBook Pro (MYD82UA) ",
      category: "Computer",
      image: "/images/1-1-removebg-preview (1).png",
      price: 3529,
      brand: "MacBook",
      MP: "Apple M1", //Processor
      RAM: 8,
      OS: "MacOS",
      INCH: 13.3,
      mAH: 2, //USB
      memory: "256 GB SSD",
      screen: "(2560x1600) Retina LED",
      SIM: 8, //Nuve sayi
    },
    {
      _id: "48",
      name: "Apple MacBook Pro M1 (MYDA2RU)",
      category: "Computer",
      image: "/images/1-1-removebg-preview (1).png",
      price: 3529,
      brand: "MacBook",
      MP: "Apple M1", //Processor
      RAM: 8,
      OS: "MacOS",
      INCH: 13.3,
      mAH: 2, //USB
      memory: "256 GB SSD",
      screen: "(2560x1600) Retina LED",
      SIM: 8, //Nuve sayi
    },
    {
      _id: "49",
      name: "Apple Macbook Pro 13 Touch Bar (MR9Q2)",
      category: "Computer",
      image: "/images/item_xl_36581124_143760079-1-removebg-preview.png",
      price: 3699,
      brand: "MacBook",
      MP: "Intel Core i5 Quad-Core 2.3GHz", //Processor
      RAM: 8,
      OS: "MacOS",
      INCH: 13.3,
      mAH: 4, //USB
      memory: "256 GB SSD",
      screen: "(2560x1600) Retina LED",
      SIM: 4, //Nuve sayi
    },
    {
      _id: "50",
      name: "Apple MacBook Pro (MYD92RU)",
      category: "Computer",
      image: "/images/item_xl_36581124_143760079-1-removebg-preview.png",
      price: 4099,
      priceDiscount: 3989,
      brand: "MacBook",
      MP: "Apple M1", //Processor
      RAM: 8,
      OS: "MacOS",
      INCH: 13.3,
      mAH: 2, //USB
      memory: "512 GB SSD",
      screen: "(2560x1600) Retina LED",
      SIM: 8, //Nuve sayi
    },
    {
      _id: "51",
      name: "Apple Macbook Pro 15 Touch Bar (MV922)",
      category: "Computer",
      image:
        "/images/apple-macbook-pro-15-touch-bar-mv922-2019_1-1-removebg-preview.png",
      price: 4999,
      brand: "MacBook",
      MP: "Apple M1", //Processor
      RAM: 16,
      OS: "MacOS",
      INCH: 15.4,
      mAH: 4, //USB
      memory: "256 GB SSD",
      screen: "(2560x1600) Retina LED",
      SIM: 6, //Nuve sayi
    },
    {
      _id: "52",
      name: "Apple Macbook Pro 15 Touch Bar (MV932)",
      category: "Computer",
      image:
        "/images/apple-macbook-pro-15-touch-bar-mv922-2019_1-1-removebg-preview.png",
      price: 5699,
      brand: "MacBook",
      MP: "Intel®Core™ i9-9880H", //Processor
      RAM: 16,
      OS: "MacOS",
      INCH: 15.4,
      mAH: 4, //USB
      memory: "512 GB SSD",
      screen: "(2560x1600) Retina LED",
      SIM: 8, //Nuve sayi
    },
    {
      _id: "53",
      name: "Apple Macbook Pro 15 Touch Bar (MV912)",
      category: "Computer",
      image:
        "/images/apple-macbook-pro-15-touch-bar-mv912-2019-removebg-preview.png",
      price: 5899,
      brand: "MacBook",
      MP: "Intel®Core™ i9-9880H", //Processor
      RAM: 16,
      OS: "MacOS",
      INCH: 15.4,
      mAH: 4, //USB
      memory: "512 GB SSD",
      screen: "(2880x1800) Retina LED",
      SIM: 8, //Nuve sayi
    },
    {
      _id: "54",
      name: "Asus VivoBook X515MA-BR062 (M05230)",
      category: "Computer",
      image:
        "/images/asus-vivobook-asus-x515na-br062-m05230_1-1-removebg-preview.png",
      price: 829,
      brand: "VivoBook",
      MP: "Intel® Celeron® N4020", //Processor
      RAM: 4,
      OS: "FreeDos",
      INCH: 15.6,
      mAH: 3, //USB
      memory: "256 GB SSD",
      screen: "HD (1366 x 768)",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "55",
      name: "Asus VivoBook D515DA-BR028 (M09710)",
      category: "Computer",
      image:
        "/images/asus-vivobook-d515da-br028-m09710_1-1-removebg-preview.png",
      price: 1089,
      brand: "VivoBook",
      MP: "AMD Ryzen™ 3 3250U", //Processor
      RAM: 4,
      OS: "FreeDos",
      INCH: 15.6,
      mAH: 3, //USB
      memory: "256 GB SSD",
      screen: "HD (1366 x 768)",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "56",
      name: "Asus UX391FA-AH027T (M00990)",
      category: "Computer",
      image: "/images/asus-ux391fa-ah027t-m00990_1-1-removebg-preview.png",
      price: 2699,
      priceDiscount: 2599,
      brand: "ZenBook",
      MP: "Intel® Core™ i5-8265U", //Processor
      RAM: 8,
      OS: "Windows 10",
      INCH: 13.3,
      mAH: 3, //USB
      memory: "512 GB SSD",
      screen: "1920x1080 FHD",
      SIM: 4, //Nuve sayi
    },
    {
      _id: "57",
      name: "Acer Aspire 3 A315-34-C3PR (NXHE3ER00N)",
      category: "Computer",
      image:
        "/images/acer-aspire-3-a315-34-c3pr-nxhe3er00n_1-1-removebg-preview.png",
      price: 799,
      brand: "Aspire",
      MP: "Intel® Celeron® N4000", //Processor
      RAM: 4,
      OS: "FreeDos",
      INCH: 15.6,
      mAH: 3, //USB
      memory: "1 TB HDD",
      screen: "HD (1366 x 768)",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "58",
      name: "Acer A315-56-35AR (NXHS5ER004)",
      category: "Computer",
      image: "/images/acer-a315-56-35ar-nxhs5er004-1-removebg-preview.png",
      price: 939,
      brand: "Aspire",
      MP: "Intel® Core™ i3-1005G1", //Processor
      RAM: 4,
      OS: "FreeDos",
      INCH: 15.6,
      mAH: 3, //USB
      memory: "256 GB SSD",
      screen: "HD (1366 x 768)",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "59",
      name: "Acer Extensa EX215-52-31VH (NXEG8ER010)",
      category: "Computer",
      image:
        "/images/acer-aspire-3-a315-34-c3pr-nxhe3er00n_1-1-removebg-preview.png",
      price: 1189,
      brand: "Aspire",
      MP: "Intel® Core™ i3-1005G1", //Processor
      RAM: 4,
      OS: "FreeDos",
      INCH: 15.6,
      mAH: 3, //USB
      memory: "1 TB HDD",
      screen: "HD (1366 x 768)",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "60",
      name: "Dell 3501-6330",
      category: "Computer",
      image: "/images/dell-3501-6330_1-1-removebg-preview.png",
      price: 1189,
      brand: "Dell",
      MP: "Intel® Core™ i3-1005G1", //Processor
      RAM: 4,
      OS: "Windows 10 Home",
      INCH: 15.6,
      mAH: 3, //USB
      memory: "256 GB SSD",
      screen: "1920x1080 FHD",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "61",
      name: "Dell 3410-2735",
      category: "Computer",
      image: "/images/dell-3501-6330_1-1-removebg-preview.png",
      price: 1559,
      brand: "Dell",
      MP: "Intel® Core™ i3-10110U", //Processor
      RAM: 4,
      OS: "Windows 10 Pro",
      INCH: 14,
      mAH: 4, //USB
      memory: "1 TB HDD",
      screen: "HD (1366 x 768)",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "62",
      name: "Dell 5587-6588",
      category: "Computer",
      image: "/images/dell_5587-6588_1-1-removebg-preview.png",
      price: 4299,
      priceDiscount: 4139,
      brand: "Dell",
      MP: "Intel®Core™ i9-8950HK", //Processor
      RAM: 16,
      OS: "FreeDos",
      INCH: 15.6,
      mAH: 4, //USB
      memory: "1TB HDD + 256GB SSD",
      screen: "1920x1080 FHD",
      SIM: 6, //Nuve sayi
    },
    {
      _id: "63",
      name: "HP 250 G7 (214B0ES)",
      category: "Computer",
      image: "/images/hp-250-g7-7dc15ea_1-1-removebg-preview.png",
      price: 749,
      brand: "Hp",
      MP: "Intel® Celeron® N4020", //Processor
      RAM: 4,
      OS: "FreeDos",
      INCH: 15.6,
      mAH: 3, //USB
      memory: "128 GB SSD",
      screen: "HD (1366 x 768)",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "64",
      name: "HP 14s-fq0005ur (1U2X5EA)",
      category: "Computer",
      image: "/images/hp-14s-fq0048ur-24c61ea_1-1-removebg-preview.png",
      price: 1199,
      brand: "Hp",
      MP: "AMD Ryzen™ 5 4500U", //Processor
      RAM: 8,
      OS: "FreeDos",
      INCH: 14,
      mAH: 3, //USB
      memory: "256 GB SSD",
      screen: "IPS 1920x1080 FHD",
      SIM: 6, //Nuve sayi
    },
    {
      _id: "65",
      name: "HP OMEN 15-DC0025UR (4GW00EA)",
      category: "Computer",
      image: "/images/hp-omen-15-dc0025ur-4gw00ea_1-1-removebg-preview.png",
      price: 3399,
      brand: "Hp",
      MP: "Intel®Core™ i7-8750Н", //Processor
      RAM: 16,
      OS: "FreeDos",
      INCH: 15.6,
      mAH: 4, //USB
      memory: "1 TB HDD + 256 GB SSD",
      screen: "1920x1080 FHD",
      SIM: 6, //Nuve sayi
    },
    {
      _id: "66",
      name: "Lenovo NB V14-IGL N4020 (82C2000YRU)",
      category: "Computer",
      image: "/images/img_0_62_2090_0_1-1-removebg-preview.png",
      price: 789,
      brand: "Nb",
      MP: "Intel Celeron N4020", //Processor
      RAM: 4,
      OS: "FreeDos",
      INCH: 14,
      mAH: 3, //USB
      memory: "1 TB HDD",
      screen: "HD (1366 x 768)",
      SIM: 2, //Nuve sayi
    },
    {
      _id: "67",
      name: "Lenovo IdeaPad 3 15IGL05 (81WQ000JRK)",
      category: "Computer",
      image:
        "/images/lenovo-ideapad-3-15igl05-81wq000jrk_1-1-removebg-preview.png",
      price: 899,
      brand: "IdeaPad",
      MP: "Intel® Celeron® N4120", //Processor
      RAM: 4,
      OS: "FreeDos",
      INCH: 15.6,
      mAH: 3, //USB
      memory: "1 TB HDD",
      screen: "HD (1366 x 768)",
      SIM: 4, //Nuve sayi
    },
    {
      _id: "68",
      name: "Lenovo Legion Y530-15ICH",
      category: "Computer",
      image:
        "/images/lenovo-legion-y530-15ich-81fv00svru_1-1-removebg-preview.png",
      price: 2499,
      priceDiscount: 2419,
      brand: "Legion",
      MP: "Intel®Core™ i7-8750Н", //Processor
      RAM: 8,
      OS: "FreeDos",
      INCH: 15.6,
      mAH: 4, //USB
      memory: "2 TB HDD",
      screen: "1920x1080 FHD",
      SIM: 6, //Nuve sayi
    },
    {
      _id: "69",
      name: "LG 32' LED Smart TV (32LM6350PLA)",
      category: "TV",
      image: "/images/lg-32-led-smart-tv-32lm6350bpla_1-1-removebg-preview.png",
      price: 649,
      brand: "Smart",
      MP: "MP3, WMA, MPEG4, HEVC (H.265), MKV, JPEG", //Format
      RAM: 32, //Diaqonal
      OS: "16:9", //Ekran Formati
      INCH: 10, // Ses gucu
      mAH: 4.65, //Cheki
      memory: "Dolby Digital, DTS", //Audio
      screen: "1920x1080 (1080p Full HD, HDR)",
      SIM: 2, //Akustik
    },
    {
      _id: "70",
      name: "LG 32' LED Smart TV (32LM6350PLA)",
      category: "TV",
      image: "/images/lg-32-led-smart-tv-32lm6350bpla_1-1-removebg-preview.png",
      price: 649,
      brand: "Smart",
      MP: "MP3, WMA, MPEG4, HEVC (H.265), MKV, JPEG", //Format
      RAM: 32, //Diaqonal
      OS: "16:9", //Ekran Formati
      INCH: 10, // Ses gucu
      mAH: 4.65, //Cheki
      memory: "Dolby Digital, DTS", //Audio
      screen: "1920x1080 (1080p Full HD, HDR)",
      SIM: 2, //Akustik
    },
    {
      _id: "71",
      name: "LG 43' LED Smart TV (43LM5700)",
      category: "TV",
      image: "/images/lg-43-led-smart-tv-43lm5700_1-1-removebg-preview.png",
      price: 949,
      brand: "Smart",
      MP: "MP3, WMA, MPEG4, HEVC (H.265), DivX, MKV, JPEG", //Format
      RAM: 43, //Diaqonal
      OS: "16:9", //Ekran Formati
      INCH: 10, // Ses gucu
      mAH: 8, //Cheki
      memory: "Dolby Digital, DTS", //Audio
      screen: "1920x1080 (1080p Full HD, HDR)",
      SIM: 2, //Akustik
    },
    {
      _id: "72",
      name: "LG 50' LED Smart NanoCell TV 4K UHD (50NANO796NF)",
      category: "TV",
      image:
        "/images/lg-50-led-smart-nanocell-tv-4k-uhd-50nano796nf_1-1-removebg-preview.png",
      price: 1449,
      brand: "Smart",
      MP: "MP3, WMA, MPEG4, HEVC (H.265), Xvid, MKV, JPEG", //Format
      RAM: 50, //Diaqonal
      OS: "16:9", //Ekran Formati
      INCH: 20, // Ses gucu
      mAH: 12.3, //Cheki
      memory: "Dolby Digital", //Audio
      screen: "3840x2160 (4K UHD, HDR)",
      SIM: 2, //Akustik
    },
  ],
};
export default data;
