export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_LIST_PRICE_FILTER_REQUEST =
  "PRODUCT_LIST_PRICE_FILTER_REQUEST";
export const PRODUCT_LIST_PRICE_FILTER_SUCCESS =
  "PRODUCT_LIST_PRICE_FILTER_SUCCESS";
export const PRODUCT_LIST_PRICE_FILTER_FAIL = "PRODUCT_LIST_PRICE_FILTER_FAIL";

export const PRODUCT_LIST_NAME_FILTER_REQUEST =
  "PRODUCT_LIST_NAME_FILTER_REQUEST";
export const PRODUCT_LIST_NAME_FILTER_SUCCESS =
  "PRODUCT_LIST_NAME_FILTER_SUCCESS";
export const PRODUCT_LIST_NAME_FILTER_FAIL = "PRODUCT_LIST_NAME_FILTER_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_FILTER_REQUEST = "PRODUCT_FILTER_REQUEST";
export const PRODUCT_FILTER_SUCCESS = "PRODUCT_FILTER_SUCCESS";
export const PRODUCT_FILTER_FAIL = "PRODUCT_FILTER_FAIL";

export const PRODUCT_FILTER_BY_ITEM_REQUEST = "PRODUCT_FILTER_BY_ITEM_REQUEST";
export const PRODUCT_FILTER_BY_ITEM_SUCCESS = "PRODUCT_FILTER_BY_ITEM_SUCCESS";
export const PRODUCT_FILTER_BY_ITEM_FAIL = "PRODUCT_FILTER_BY_ITEM_FAIL";

export const PRODUCT_FILTER_BY_PRICE_REQUEST =
  "PRODUCT_FILTER_BY_PRICE_REQUEST";
export const PRODUCT_FILTER_BY_PRICE_SUCCESS =
  "PRODUCT_FILTER_BY_PRICE_SUCCESS";
export const PRODUCT_FILTER_BY_PRICE_FAIL = "PRODUCT_FILTER_BY_PRICE_FAIL";

export const PRODUCT_FILTER_BY_PRICE_CATEGORY_REQUEST =
  "PRODUCT_FILTER_BY_PRICE_CATEGORY_REQUEST";
export const PRODUCT_FILTER_BY_PRICE_CATEGORY_SUCCESS =
  "PRODUCT_FILTER_BY_PRICE_CATEGORY_SUCCESS";
export const PRODUCT_FILTER_BY_PRICE_CATEGORY_FAIL =
  "PRODUCT_FILTER_BY_PRICE_CATEGORY_FAIL";

export const PRODUCT_SORT_BY_NAME_CATEGORY_REQUEST =
  "PRODUCT_SORT_BY_NAME_CATEGORY_REQUEST";
export const PRODUCT_SORT_BY_NAME_CATEGORY_SUCCESS =
  "PRODUCT_SORT_BY_NAME_CATEGORY_SUCCESS";
export const PRODUCT_SORT_BY_NAME_CATEGORY_FAIL =
  "PRODUCT_SORT_BY_NAME_CATEGORY_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_FAIL = "PRODUCT_SEARCH_FAIL";
export const PRODUCT_SEARCH_RESET = "PRODUCT_SEARCH_RESET";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const PRODUCT_DETAILS_RESET = "PRODUCT_DETAILS_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
